spring:
  application:
    name: movies-shell
  shell:
    interactive:
      enabled: true

http.client.ssl:
  trust-store: keystore.p12
  trust-store-password: secret

movies-api:
  url: https://localhost:8443/api/movies

logging.level.root: off
