spring:
  application:
    name: movies-shell
  ssl:
    bundle:
      jks:
        my-client-bundle:
          truststore:
            location: classpath:keystore.p12
            password: secret
  shell:
    interactive:
      enabled: true

movies-api:
  url: https://localhost:8443

logging.level.root: off
